### ISSUE TITLE
History gets strange after editing it a few times

### ISSUE THREAD

**Issue by Kbam7** [Kbam7/42sh#15]
Im just leaving this note here for future reference. 

If you open the shell and enter something, then press up to go to the previous command, delete it, then execute another command and go up through the history, you should see that the characters are corrupt from which ever history item was edited. If you keep adding more to the history the strings which were edited get corrupt.

As a note, if you type something and press up, there is no way to get that command you were just typing back. 

Also, it somehow adds 2 of the same item at some point. Like if you edit a few things, execute another couple commands and check the history after each command, you will see it duplicates items or something.

**Comment by tonmanayo** [comment]
down arrow didnt have a strdup, ive fixed it on my side
