### ISSUE TITLE
Need to get scrolling working in terminal

### ISSUE THREAD

**Issue by Kbam7** [Kbam7/42sh#16]
I think the basic infrastructure is there. Just got to call the right term capability string when a scroll is received as input. The read buffer in the `buffer()` function has been increased to '4096' as a test number. My highest recording of chars input from a single scroll was '20', that may be just because of the settings on my laptop(Ubuntu), so maybe some further testing is needed. But basically, a scrolls input is a repetition of the up or down keys. That's why when we used to scroll, the history used to move as well.

**Comment by tonmanayo** [comment]
scrolling works in iterm
