### ISSUE TITLE
env setenv unsetenv 

### ISSUE THREAD

**Issue by tonmanayo** [Kbam7/42sh#20]
unsetenv malloc error
setenv cursos x2
setenv no error checking if only 2 commands

i think ill add my old setenv and unsetenv env see if it works

**Comment by Kbam7** [comment]
Okay cool. Im going to have a look at it now, see if its maybe a silly mistake. I know it worked well before the merge. So its just a couple bugs.

**Comment by Kbam7** [comment]
So an update, I managed to sort out the read errors and stuff with the env funcs. So they should be good. If there are still any of the problems you mentioned earlier, please give an example of what you did and i will see what i can do. :)
