### ISSUE TITLE
Operators

### ISSUE THREAD

**Issue by kylegani** [Kbam7/42sh#67]
Printing out weird string when running operators

![screen shot 2016-09-09 at 10 14 19 am](https://cloud.githubusercontent.com/assets/18421182/18380130/340678a0-7676-11e6-812a-eacaebac7ba9.png)

**Comment by Kbam7** [comment]
Just some debugging. I will remove it and update the master. Sorry about that

**Comment by Kbam7** [comment]
Removed the debug
